<?php
/** @var Zend\View\Renderer\PhpRenderer $this */
?>
<h1>Авторизация</h1>

<div class="row">
    <?php
    $form = $this->loginForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/login'));
    $form->setAttribute('method', 'post');
    ?>

    <?php echo $this->form()->openTag($form) ?>
    <div class="form-group">
        <?php echo $this->formElementErrors($form->get('identity')) ?>
        <?php echo $this->formLabel($form->get('identity')) ?>
        <?php echo $this->formInput($form->get('identity')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('credential')) ?>
        <?php echo $this->formInput($form->get('credential')) ?>
    </div>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>"/>
    <?php endif ?>

    <?php echo $this->formButton($form->get('submit')) ?>


    <?php echo $this->form()->closeTag() ?>
</div>

<?php if ($this->enableRegistration) { ?>
    <div class="row">
        Не зарегистрированы? <a
            href="<?php echo $this->url('zfcuser/register').($this->redirect ? '?redirect='.$this->redirect : '') ?>">Регистрация!</a>
    </div>
<?php } ?>
