<?php
/** @var Zend\View\Renderer\PhpRenderer $this */
?>
<h1>Регистрация</h1>
<div class="row">
    <?php
    if (!$this->enableRegistration) {
        print "Регистрация отключена";

        return;
    }
    $form = $this->registerForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/register'));
    $form->setAttribute('method', 'post');
    ?>

    <?php echo $this->form()->openTag($form) ?>

    <?php foreach ($form as $element) { ?>
        <?php if (!$element instanceof Zend\Form\Element\Button) { ?>
            <?php echo $this->formLabel($element) ?>
        <?php } ?>
        <?php if ($element instanceof Zend\Form\Element\Button) { ?>
            <?php echo $this->formButton($element) ?>
        <?php } elseif ($element instanceof Zend\Form\Element\Captcha) { ?>
            <?php echo $this->formCaptcha($element).$this->formElementErrors($element) ?>
        <?php } else { ?>
            <?php echo $this->formInput($element).$this->formElementErrors($element) ?>
        <?php } ?>
    <?php } ?>

    <?php if ($this->redirect) { ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>"/>
    <?php } ?>
    <?php echo $this->form()->closeTag() ?>
</div>