<?php
/** @var Zend\View\Renderer\PhpRenderer $this */
/** @var \Application\Form\Doc $form */

$form->prepare();
?>

<?= $this->form()->openTag($form) ?>
<?php
foreach ($form as $element) {
    if ($element instanceof Zend\Form\Element\Checkbox) {
        echo '<div class="checkbox">';
    }
    if (!$element instanceof Zend\Form\Element\Button) {
        echo $this->formLabel($element);
    }

    echo $this->formElement($element).$this->formElementErrors($element);
    if ($element instanceof Zend\Form\Element\Checkbox) {
        echo '</div>';
    }
}
?>
<?= $this->partial('application/index/files') ?>
<br>
<div class="form-group">
    <button type="submit" name="save" class="btn btn-default">
        Сохранить
    </button>
    <?php
    if ($this->doc && !$doc->getRegisterNumber()) {
    ?>
    <input type="submit" name="register" class="btn btn-success" value="Регистрация">
    <?php } ?>
</div>

<?= $this->form()->closeTag() ?>
<script type="text/javascript">
    $(document).ready(function() {
        $("#keywords").tagit();
    });
</script>
