<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Документооборот</h3>
            </div>
            <div class="panel-body">
                <p>Для того, чтобы воспользоваться сервисом необходимо авторизоваться</p>
                <p><a class="btn btn-success pull-right" href="<?= $this->url('zfcuser/login') ?>">Авторизация &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
