<?php
/** @var Zend\View\Renderer\PhpRenderer $this */
/** @var int $page */
?>
<div class="col-md-3">
    <div class="list-group">
        <a href="<?= $this->url('docs', ['action' => 'add-doc']) ?>"
           class="list-group-item <?= $page == 4 ? 'active' : '' ?>">Создать документ</a>
        <?php
        foreach(\Application\Entity\Doc::getDocTypeNames() as $key => $val) {
        ?>
        <a href="<?= $this->url('docs', ['action' => 'view-docs', 'type' => $key]) ?>"
           class="list-group-item <?= $page == $key ? 'active' : '' ?>"><?= $val ?></a>
        <?php } ?>
        <a href="<?= $this->url('docs', ['action' => 'search-docs']) ?>"
           class="list-group-item <?= $page == 5 ? 'active' : '' ?>">Поиск по документам</a>
    </div>
</div>