<?php
/** @var Zend\View\Renderer\PhpRenderer $this */
?>
<div class="row">
    <?= $this->partial('application/index/left-menu', ['page' => 5]); ?>
    <div class="col-md-9">
        <h1>Поиск по документам</h1>
        <form action="">
            <div class="form-group">
                <input class="form-control col-xs-10" style="width: 80%" type="text" name="search" value="<?= $this->search ?>"
                       placeholder="Имя документа или ключевое слово">
                <input type="submit" name="go" value="Искать" class="btn btn-primary col-xs-2" style="width: 20%">
            </div>
            <details style="display: block">Доступные ключевые слова: <?php
                foreach ($this->keywords as $keyword) {
                    ?>
                    <a href="<?= $this->url('docs', ['action' => 'search-docs']) ?>?search=<?= $keyword ?>"><span
                            class="label label-info"><?= $keyword ?></span></a>
                    <?php
                }
                ?></details>
        </form>
        <?= $this->partial('application/index/docs-table', ['docs' => $this->docs, 'notMessage' => true]) ?>
    </div>
</div>
