<?php
/** @var Zend\View\Renderer\PhpRenderer $this */

?>
<div class="row">
    <?= $this->partial('application/index/left-menu', ['page' => $this->type]); ?>
    <div class="col-md-9">
        <h1><?= \Application\Entity\Doc::getDocTypeNames()[$this->type] ?></h1>
        <?= $this->partial('application/index/docs-table') ?>
    </div>
</div>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-9">
        <?= $this->paginationControl($this->paginator, 'Sliding', 'application/index/pager.phtml', [
            'route' => 'docs',
            'action' => 'view-docs',
            'type' => $this->type
        ]); ?>
    </div>
</div>